name: MEXC Futures Telegram Bot

# Her 1 saatte bir çalışacak
on:
  schedule:
    - cron: '0 * * * *'   # Her saat başı
  workflow_dispatch:       # Manuel çalıştırma opsiyonu

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Repo'yu checkout et
        uses: actions/checkout@v3

      - name: Python kurulumu
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Gerekli paketleri yükle
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests

      - name: Botu çalıştır
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          python main.py
